#if !canImport(ObjectiveC)
import XCTest

extension ComponentIdentifierTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ComponentIdentifierTests = [
        ("testMirrorAsStableIdentifier", testMirrorAsStableIdentifier),
        ("testStringDescribingAsStableIdentifier", testStringDescribingAsStableIdentifier)
    ]
}

extension ComponentInstanceProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ComponentInstanceProviderTests = [
        ("testProviderReturnsTheInstance", testProviderReturnsTheInstance),
        ("testProvidersWithDifferentInstanceHaveDifferentIdentifier", testProvidersWithDifferentInstanceHaveDifferentIdentifier),
        ("testProvidersWithSameInstanceHaveSameIdentifier", testProvidersWithSameInstanceHaveSameIdentifier)
    ]
}

extension ComponentSingletonProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ComponentSingletonProviderTests = [
        ("testProviderReturnsAnInstanceOfType", testProviderReturnsAnInstanceOfType),
        ("testProviderReturnsSameInstanceEachTime", testProviderReturnsSameInstanceEachTime),
        ("testProvidersWithDifferentTypeHaveDifferentIdentifier", testProvidersWithDifferentTypeHaveDifferentIdentifier),
        ("testProvidersWithSameTypeHaveDifferentIdentifier", testProvidersWithSameTypeHaveDifferentIdentifier)
    ]
}

extension ComponentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ComponentTests = [
        ("testComponentIdentifier", testComponentIdentifier)
    ]
}

extension ComponentTypeProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ComponentTypeProviderTests = [
        ("testProviderReturnsAnInstanceOfType", testProviderReturnsAnInstanceOfType),
        ("testProviderReturnsNewInstanceEachTime", testProviderReturnsNewInstanceEachTime),
        ("testProvidersWithDifferentTypeHaveDifferentIdentifier", testProvidersWithDifferentTypeHaveDifferentIdentifier),
        ("testProvidersWithSameTypeHaveSameIdentifier", testProvidersWithSameTypeHaveSameIdentifier)
    ]
}

extension DynamicComponentProviderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DynamicComponentProviderTests = [
        ("testProviderReturnsTheInstance", testProviderReturnsTheInstance),
        ("testProvidersWithDifferentMethodsHaveDifferentIdentifier", testProvidersWithDifferentMethodsHaveDifferentIdentifier),
        ("testProvidersWithSameMethodHaveSameIdentifier", testProvidersWithSameMethodHaveSameIdentifier)
    ]
}

extension EntityCreationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EntityCreationTests = [
        ("testBulkCreateEntitiesMultipleComponents", testBulkCreateEntitiesMultipleComponents),
        ("testBulkCreateEntitiesOneComponent", testBulkCreateEntitiesOneComponent),
        ("testCreateEntityMultipleComponents", testCreateEntityMultipleComponents),
        ("testCreateEntityOneComponent", testCreateEntityOneComponent)
    ]
}

extension EntityIdGenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EntityIdGenTests = [
        ("testGenerateWithInitialIds", testGenerateWithInitialIds),
        ("testGeneratorDefaultInit", testGeneratorDefaultInit),
        ("testGeneratorMarkUnused", testGeneratorMarkUnused),
        ("testGeneratorWithDefaultEmptyCollection", testGeneratorWithDefaultEmptyCollection),
        ("testLinearIncrement", testLinearIncrement)
    ]
}

extension EntityStateMachineTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EntityStateMachineTests = [
        ("testCallChangeStateWithSameNameLeavesEntityComponentsIntact", testCallChangeStateWithSameNameLeavesEntityComponentsIntact),
        ("testCreateStateAddsState", testCreateStateAddsState),
        ("testCreateStateDoesNotChangeState", testCreateStateDoesNotChangeState),
        ("testEnterSecondStateAddsSecondStatesComponents", testEnterSecondStateAddsSecondStatesComponents),
        ("testEnterSecondStateDoesNotRemoveOverlappingComponents", testEnterSecondStateDoesNotRemoveOverlappingComponents),
        ("testEnterSecondStateRemovesDifferentComponentsOfSameType", testEnterSecondStateRemovesDifferentComponentsOfSameType),
        ("testEnterSecondStateRemovesFirstStatesComponents", testEnterSecondStateRemovesFirstStatesComponents),
        ("testEnterStateAddsStatesComponents", testEnterStateAddsStatesComponents)
    ]
}

extension EntityStateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EntityStateTests = [
        ("testAddWithInstanceQualifierCreatesInstanceProvider", testAddWithInstanceQualifierCreatesInstanceProvider),
        ("testAddWithMethodQualifierCreatesDynamicProvider", testAddWithMethodQualifierCreatesDynamicProvider),
        ("testAddWithNoQualifierCreatesTypeProvider", testAddWithNoQualifierCreatesTypeProvider),
        ("testAddWithSingletonQualifierCreatesSingletonProvider", testAddWithSingletonQualifierCreatesSingletonProvider),
        ("testAddWithTypeQualifierCreatesTypeProvider", testAddWithTypeQualifierCreatesTypeProvider),
        ("testGetReturnsDynamicProvider", testGetReturnsDynamicProvider),
        ("testGetReturnsInstanceProvider", testGetReturnsInstanceProvider),
        ("testGetReturnsPassedProvider", testGetReturnsPassedProvider),
        ("testGetReturnsSingletonProvider", testGetReturnsSingletonProvider),
        ("testGetReturnsTypeProvider", testGetReturnsTypeProvider),
        ("testGetReturnsTypeProviderByDefault", testGetReturnsTypeProviderByDefault),
        ("testHasReturnsFalseForNotCreatedProvider", testHasReturnsFalseForNotCreatedProvider),
        ("testHasReturnsTrueForCreatedProvider", testHasReturnsTrueForCreatedProvider)
    ]
}

extension EntityTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__EntityTests = [
        ("testAllComponentsOfEntity", testAllComponentsOfEntity),
        ("testEntityEquality", testEntityEquality),
        ("testEntityIdentifierAndIndex", testEntityIdentifierAndIndex),
        ("testEntityIdGenerator", testEntityIdGenerator),
        ("testEntitySubscripts", testEntitySubscripts),
        ("testRemoveAllComponentsFromEntity", testRemoveAllComponentsFromEntity)
    ]
}

extension Family1Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Family1Tests = [
        ("testComponentIteration", testComponentIteration),
        ("testEntityComponentIteration", testEntityComponentIteration),
        ("testEntityIteration", testEntityIteration),
        ("testFamilyDecoding", testFamilyDecoding),
        ("testFamilyEncoding", testFamilyEncoding),
        ("testFamilyFailDecoding", testFamilyFailDecoding),
        ("testMemberCreation", testMemberCreation),
        ("testMemberCreationBuilder", testMemberCreationBuilder)
    ]
}

extension Family2Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Family2Tests = [
        ("testComponentIteration", testComponentIteration),
        ("testEntityComponentIteration", testEntityComponentIteration),
        ("testEntityIteration", testEntityIteration),
        ("testFamilyDecoding", testFamilyDecoding),
        ("testFamilyEncoding", testFamilyEncoding),
        ("testFamilyFailDecoding", testFamilyFailDecoding),
        ("testMemberCreation", testMemberCreation),
        ("testMemberCreationBuilder", testMemberCreationBuilder)
    ]
}

extension Family3Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Family3Tests = [
        ("testComponentIteration", testComponentIteration),
        ("testEntityComponentIteration", testEntityComponentIteration),
        ("testEntityIteration", testEntityIteration),
        ("testFamilyDecoding", testFamilyDecoding),
        ("testFamilyEncoding", testFamilyEncoding),
        ("testFamilyFailDecoding", testFamilyFailDecoding),
        ("testMemberCreation", testMemberCreation),
        ("testMemberCreationBuilder", testMemberCreationBuilder)
    ]
}

extension Family4Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Family4Tests = [
        ("testComponentIteration", testComponentIteration),
        ("testEntityComponentIteration", testEntityComponentIteration),
        ("testEntityIteration", testEntityIteration),
        ("testFamilyDecoding", testFamilyDecoding),
        ("testFamilyEncoding", testFamilyEncoding),
        ("testFamilyFailDecoding", testFamilyFailDecoding),
        ("testMemberCreation", testMemberCreation),
        ("testMemberCreationBuilder", testMemberCreationBuilder)
    ]
}

extension Family5Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Family5Tests = [
        ("testComponentIteration", testComponentIteration),
        ("testEntityComponentIteration", testEntityComponentIteration),
        ("testEntityIteration", testEntityIteration),
        ("testFamilyDecoding", testFamilyDecoding),
        ("testFamilyEncoding", testFamilyEncoding),
        ("testFamilyFailDecoding", testFamilyFailDecoding),
        ("testMemberCreation", testMemberCreation),
        ("testMemberCreationBuilder", testMemberCreationBuilder)
    ]
}

extension Family6Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Family6Tests = [
        ("testComponentIteration", testComponentIteration),
        ("testEntityComponentIteration", testEntityComponentIteration),
        ("testEntityIteration", testEntityIteration),
        ("testFamilyDecoding", testFamilyDecoding),
        ("testFamilyEncoding", testFamilyEncoding),
        ("testFamilyFailDecoding", testFamilyFailDecoding),
        ("testMemberCreation", testMemberCreation),
        ("testMemberCreationBuilder", testMemberCreationBuilder)
    ]
}

extension Family7Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Family7Tests = [
        ("testComponentIteration", testComponentIteration),
        ("testEntityComponentIteration", testEntityComponentIteration),
        ("testEntityIteration", testEntityIteration),
        ("testFamilyDecoding", testFamilyDecoding),
        ("testFamilyEncoding", testFamilyEncoding),
        ("testFamilyFailDecoding", testFamilyFailDecoding),
        ("testMemberCreation", testMemberCreation),
        ("testMemberCreationBuilder", testMemberCreationBuilder)
    ]
}

extension Family8Tests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__Family8Tests = [
        ("testComponentIteration", testComponentIteration),
        ("testEntityComponentIteration", testEntityComponentIteration),
        ("testEntityIteration", testEntityIteration),
        ("testFamilyDecoding", testFamilyDecoding),
        ("testFamilyEncoding", testFamilyEncoding),
        ("testFamilyFailDecoding", testFamilyFailDecoding),
        ("testMemberCreation", testMemberCreation),
        ("testMemberCreationBuilder", testMemberCreationBuilder)
    ]
}

extension FamilyCodingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FamilyCodingTests = [
        ("testDecodeFamily4", testDecodeFamily4),
        ("testDecodeFamily5", testDecodeFamily5),
        ("testDecodingFamily1", testDecodingFamily1),
        ("testDecodingFamily2", testDecodingFamily2),
        ("testDecodingFamily3", testDecodingFamily3),
        ("testEncodeFamily2", testEncodeFamily2),
        ("testEncodeFamily3", testEncodeFamily3),
        ("testEncodeFamily4", testEncodeFamily4),
        ("testEncodeFamily5", testEncodeFamily5),
        ("testEncodingFamily1", testEncodingFamily1),
        ("testFailDecodingFamily", testFailDecodingFamily)
    ]
}

extension FamilyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FamilyTests = [
        ("testFamilyAbandoned", testFamilyAbandoned),
        ("testFamilyBulkDestroy", testFamilyBulkDestroy),
        ("testFamilyCreateMembers", testFamilyCreateMembers),
        ("testFamilyCreation", testFamilyCreation),
        ("testFamilyDestroyMembers", testFamilyDestroyMembers),
        ("testFamilyExchange", testFamilyExchange),
        ("testFamilyLateMember", testFamilyLateMember),
        ("testFamilyMemberBasicIteration", testFamilyMemberBasicIteration),
        ("testFamilyReuse", testFamilyReuse)
    ]
}

extension FamilyTraitsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__FamilyTraitsTests = [
        ("testTraitCommutativity", testTraitCommutativity),
        ("testTraitMatching", testTraitMatching)
    ]
}

extension HashingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HashingTests = [
        ("testCollisionsInCritialRange", testCollisionsInCritialRange),
        ("testStringHashes", testStringHashes)
    ]
}

extension NexusTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__NexusTests = [
        ("testComponentCreation", testComponentCreation),
        ("testComponentDeletion", testComponentDeletion),
        ("testComponentRetrieval", testComponentRetrieval),
        ("testComponentUniqueness", testComponentUniqueness),
        ("testEntityCreate", testEntityCreate),
        ("testEntityDestroy", testEntityDestroy)
    ]
}

extension SingleTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SingleTests = [
        ("testSingleCreation", testSingleCreation),
        ("testSingleCreationOnExistingFamilyMember", testSingleCreationOnExistingFamilyMember),
        ("testSingleEntityAndComponentCreation", testSingleEntityAndComponentCreation),
        ("testSingleReuse", testSingleReuse)
    ]
}

extension SparseSetTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SparseSetTests = [
        ("testAlternativeKey", testAlternativeKey),
        ("testEquality", testEquality),
        ("testSparseSetAdd", testSparseSetAdd),
        ("testSparseSetAddAndReplace", testSparseSetAddAndReplace),
        ("testSparseSetClear", testSparseSetClear),
        ("testSparseSetDoubleRemove", testSparseSetDoubleRemove),
        ("testSparseSetGet", testSparseSetGet),
        ("testSparseSetNonCongiuousData", testSparseSetNonCongiuousData),
        ("testSparseSetReduce", testSparseSetReduce),
        ("testSparseSetRemove", testSparseSetRemove),
        ("testSparseSetRemoveAndAdd", testSparseSetRemoveAndAdd),
        ("testSparseSetRemoveNonPresent", testSparseSetRemoveNonPresent),
        ("testStartEndIndex", testStartEndIndex),
        ("testSubscript", testSubscript)
    ]
}

extension StateComponentMappingTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StateComponentMappingTests = [
        ("testAddAddsProviderToState", testAddAddsProviderToState),
        ("testAddReturnsSameMappingForDifferentComponentTypes", testAddReturnsSameMappingForDifferentComponentTypes),
        ("testAddReturnsSameMappingForSameComponentType", testAddReturnsSameMappingForSameComponentType)
    ]
}

extension SystemsTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SystemsTests = [
        ("testSystemsUpdate", testSystemsUpdate)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ComponentIdentifierTests.__allTests__ComponentIdentifierTests),
        testCase(ComponentInstanceProviderTests.__allTests__ComponentInstanceProviderTests),
        testCase(ComponentSingletonProviderTests.__allTests__ComponentSingletonProviderTests),
        testCase(ComponentTests.__allTests__ComponentTests),
        testCase(ComponentTypeProviderTests.__allTests__ComponentTypeProviderTests),
        testCase(DynamicComponentProviderTests.__allTests__DynamicComponentProviderTests),
        testCase(EntityCreationTests.__allTests__EntityCreationTests),
        testCase(EntityIdGenTests.__allTests__EntityIdGenTests),
        testCase(EntityStateMachineTests.__allTests__EntityStateMachineTests),
        testCase(EntityStateTests.__allTests__EntityStateTests),
        testCase(EntityTests.__allTests__EntityTests),
        testCase(Family1Tests.__allTests__Family1Tests),
        testCase(Family2Tests.__allTests__Family2Tests),
        testCase(Family3Tests.__allTests__Family3Tests),
        testCase(Family4Tests.__allTests__Family4Tests),
        testCase(Family5Tests.__allTests__Family5Tests),
        testCase(Family6Tests.__allTests__Family6Tests),
        testCase(Family7Tests.__allTests__Family7Tests),
        testCase(Family8Tests.__allTests__Family8Tests),
        testCase(FamilyCodingTests.__allTests__FamilyCodingTests),
        testCase(FamilyTests.__allTests__FamilyTests),
        testCase(FamilyTraitsTests.__allTests__FamilyTraitsTests),
        testCase(HashingTests.__allTests__HashingTests),
        testCase(NexusTests.__allTests__NexusTests),
        testCase(SingleTests.__allTests__SingleTests),
        testCase(SparseSetTests.__allTests__SparseSetTests),
        testCase(StateComponentMappingTests.__allTests__StateComponentMappingTests),
        testCase(SystemsTests.__allTests__SystemsTests)
    ]
}
#endif
