#if !canImport(ObjectiveC)
import XCTest

extension ComponentIdentifierTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ComponentIdentifierTests = [
        ("testMeasureComponentIdentifier", testMeasureComponentIdentifier),
        ("testMeasureStaticComponentIdentifier", testMeasureStaticComponentIdentifier)
    ]
}

extension HashingPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HashingPerformanceTests = [
        ("testMeasureBernsteinDjb2", testMeasureBernsteinDjb2),
        ("testMeasureCombineHash", testMeasureCombineHash),
        ("testMeasureSDBM", testMeasureSDBM),
        ("testMeasureSetOfSetHash", testMeasureSetOfSetHash),
        ("testMeasureSingerDjb2", testMeasureSingerDjb2),
        ("testMeasureSwiftHasher", testMeasureSwiftHasher)
    ]
}

extension TypeIdentifierPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TypeIdentifierPerformanceTests = [
        ("testPerformanceHash", testPerformanceHash),
        ("testPerformanceMirrorReflectingDescription", testPerformanceMirrorReflectingDescription),
        ("testPerformanceObjectIdentifier", testPerformanceObjectIdentifier),
        ("testPerformanceStringDescribing", testPerformanceStringDescribing),
        ("testPerformanceStringReflecting", testPerformanceStringReflecting)
    ]
}

extension TypedFamilyPerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TypedFamilyPerformanceTests = [
        ("testMeasureTraitMatching", testMeasureTraitMatching),
        ("testPerformanceArray", testPerformanceArray),
        ("testPerformanceTypedFamilyEntities", testPerformanceTypedFamilyEntities),
        ("testPerformanceTypedFamilyEntityFiveComponents", testPerformanceTypedFamilyEntityFiveComponents),
        ("testPerformanceTypedFamilyEntityFourComponents", testPerformanceTypedFamilyEntityFourComponents),
        ("testPerformanceTypedFamilyEntityOneComponent", testPerformanceTypedFamilyEntityOneComponent),
        ("testPerformanceTypedFamilyEntityThreeComponents", testPerformanceTypedFamilyEntityThreeComponents),
        ("testPerformanceTypedFamilyEntityTwoComponents", testPerformanceTypedFamilyEntityTwoComponents),
        ("testPerformanceTypedFamilyFiveComponents", testPerformanceTypedFamilyFiveComponents),
        ("testPerformanceTypedFamilyFourComponents", testPerformanceTypedFamilyFourComponents),
        ("testPerformanceTypedFamilyOneComponent", testPerformanceTypedFamilyOneComponent),
        ("testPerformanceTypedFamilyThreeComponents", testPerformanceTypedFamilyThreeComponents),
        ("testPerformanceTypedFamilyTwoComponents", testPerformanceTypedFamilyTwoComponents)
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    [
        testCase(ComponentIdentifierTests.__allTests__ComponentIdentifierTests),
        testCase(HashingPerformanceTests.__allTests__HashingPerformanceTests),
        testCase(TypeIdentifierPerformanceTests.__allTests__TypeIdentifierPerformanceTests),
        testCase(TypedFamilyPerformanceTests.__allTests__TypedFamilyPerformanceTests)
    ]
}
#endif
